/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jaggedArray */

#ifndef _Included_jaggedArray
#define _Included_jaggedArray
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
